### ISSUE TITLE
Adding EDF version of the ECoG data

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-misc-data#2]
@larsoner is it possible to add an EDF version using the gist here: https://gist.github.com/skjerns/bc660ef59dca0dbd53f00ed38c42f6be

This would just create a fake EEG data with the corresponding electrodes in sample_ecog.mat.

**Reason:**
The reason is that inside mne-bids, right now the package needs an EEG file to be in an accepted "rawfile" format when performing writing. For EEG/MEG, these are readily available, but for iEEG this is only in the form of EDF and BV. This isn't an issue when using the existing EDF/BV datasets in mne, but none have electrode coordinates (i.e. a montage). The sample_ecog.mat  here has a montage, but no corresponding iEEG  data.

To make a good iEEG example in mne-bids, it would be helpful instead to just get a fake EDF file that has the same data as in sample_ecog.mat, and then sample_ecog.mat has the fake electrode coordinates.

**Reference issues:** 
- https://github.com/mne-tools/mne-bids/issues/404
- https://github.com/mne-tools/mne-bids/pull/390

**Comment by larsoner** [comment]
Is it possible to get some real data instead?

**Comment by larsoner** [comment]
... if not, then I would not even bother keeping `sample_ecog.mat` (in the long run) but replace it completely with a `.edf` file instead. Some process like:

1. Create PR here to replace `sample_ecog.mat` with a one-sample EDF file with the iEEG electrode locations
2. Create PR to MNE to fix EDF+iEEG electrode support, using (temporarily) the `mne-misc-data` fork+branch with the EDF file
3. Once the MNE PR is settled (i.e., the hard part), merge the data PR to here and make the MNE PR use the proper `mne-tools/mne-misc-data` with a new version number
4. Merge the MNE PR

Even in the case of real data we can follow this pattern, and then decide separately if there is any reason to keep the `sample_ecog.mat` file around (probably not).

**Comment by adam2392** [comment]
> Is it possible to get some real data instead?

I have... SEEG data, but that's not as nice for visualization as ECoG. I could say... substitute "real" data but fake it by changing it to the electrodes inside `sample_ecog.mat`? What's the motivation of substituting real data instead?

> ... if not, then I would not even bother keeping `sample_ecog.mat` (in the long run) but replace it completely with a `.edf` file instead. Some process like:

If that is the case, we still need a way to store electrode coordinates, since EDF files don't carry this normally?

The current https://mne.tools/stable/auto_tutorials/misc/plot_ecog.html depends on sample_ecog.mat

**Comment by larsoner** [comment]
> I have... SEEG data, but that's not as nice for visualization as ECoG. I could say... substitute "real" data but fake it by changing it to the electrodes inside sample_ecog.mat? What's the motivation of substituting real data instead?

It's nicer to use real data in examples and for testing where possible. Having new, real data for an sEEG would be nice to have in MNE anyway. Even if we just visualize the electrode locations in the brain it's cool to show.

I say we follow the process I outlined above with your real data, but instead of "adding an EDF file with electrode locations", add data in whatever format you're supposed to use with BIDS to get the data plus electrode locations (EDF + some sidecar JSON file? I don't know...)

**Comment by agramfort** [comment]
maybe @libertyh can point to such a dataset we could use?

**Comment by adam2392** [comment]
It's okay I hacked together a "trimmed" ecog/seeg dataset derived from real data.

@larsoner how does one substitute the PR version of mne-misc  data? In https://github.com/mne-tools/mne-python/blob/5b7d8170804167b81965cb30c65f8abbd8ebedf5/mne/datasets/utils.py#L248-L274 I'm guessing I have to change something? However, how do I point to a PR?

In addition, is there anything else to change?

**Comment by larsoner** [comment]
Maybe it would be better to add it as a proper separate dataset actually. Then you would "just" follow the changes from this PR as a template:

https://github.com/mne-tools/mne-python/pull/7018

**Comment by larsoner** [comment]
Ahh, just saw that the data are quite short (10-30 sec). So indeed maybe `misc` is still better, since it's not a real/complete dataset and is more just for demo purposes

**Comment by larsoner** [comment]
> 

You can change:
```
        misc='https://codeload.github.com/mne-tools/mne-misc-data/'
             'tar.gz/%s' % releases['misc'],
```
to
```
        misc='https://github.com/adam2392/mne-misc-data/tarball/seeg',
```
and I think it should work
