### ISSUE TITLE
Add an eyetracking 

### ISSUE THREAD

**Issue by scott-huberty** [mne-tools/mne-misc-data#22]
Hi @larsoner - Can I open a PR to add an eyetracking file to mne-misc-data? It's for the documentation [being bulit in the eytracking PR](https://github.com/mne-tools/mne-python/pull/11152?notification_referrer_id=NT_kwDOAyCByrM0MzcwNjYxOTA0OjUyNDYyMDI2#issuecomment-1449102125).

The file is small - only 10mb

Thanks!

**Comment by larsoner** [comment]
Yes please do!
